config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :items
  resources :carts
  resources :orders
  resources :join_table_cart_items
  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :items
	has_many :join_table_cart_items
	
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :carts
	has_many :orders
	validates :title, presence: true, length: { in: 3..14}
    validates :description, presence: true, length: {minimum: 10, maximum: 100}
    validates :image_url, presence: true, format: {with: /\.(png|jpg|gif)\Z/i}
end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord
	belongs_to :item
	belongs_to :cart
end

app/models/join_table_order_item.rb
class JoinTableOrderItem < ApplicationRecord
	belongs_to :item
	belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :items
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


	after_create :welcome_send
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  has_many :items, through: :cart
  has_many :orders
  has_one :cart

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_paramters, if: :devise_controller?

  protected
    def configure_permitted_paramters

        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description, :age])

        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :description, :age,
        :email, :password])

    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :set_cart, only: [:show]
 
  def index
    @carts = Cart.all
  end

  def show
    @cart = Cart.find(params[:id])
    def sum
      sum = 0
        for i in (0..@cart.join_table_cart_items.length-1)
          sum = sum + @cart.join_table_cart_items[i].item.price
        end
      return sum 
    end
    @sum = sum
  end

  def new
  end

  def create
    @item = Item.find(params[:item_id])
    @join_table_cart_items = @cart.join_table_cart_item.new(item: item)
  end

  def update
  end

  def destroy
  end

  def edit
  
  end
  
  private

    def set_cart
      @cart = Cart.find_by(id: session[:cart_id]) || Cart.create
        session[:cart_id] ||= @cart.id
    end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

   def index
    @items = Item.all
    puts @items
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  def edit
  end

end

app/controllers/join_table_cart_items_controller.rb
class JoinTableCartItemsController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_cart, only: [:create]
  def index

  end

  def show
  end

  def new
  end

  def create
    item = Item.find(params['data_value'])
    @cart = Cart.find_by(user_id:current_user.id)
    if_item_exist = @cart.join_table_cart_items.find_by(item_id: item.id)
    
    if !if_item_exist
      @join_table_cart_items = @cart.join_table_cart_items.new(item: item)
      respond_to do |format|
        if @join_table_cart_items.save
          format.html {redirect_to @join_table_cart_items.cart, notice: 'Item a été créer avec succés'}
          format.json { render :show, status: :created, location: @join_table_cart_items}
        end
      end
    else
         
    end  
    
    
  end

  def update
  end

  def destroy
    item = JoinTableCartItem.find(params[:id])
    item.destroy
    @cart = Cart.find_by(user_id:current_user.id)
    redirect_to cart_path(@cart.id)
  end

  def edit
  end

  private

  def set_cart
    @cart = Cart.find_by(id: session[:cart_id]) || Cart.create
      session[:cart_id] ||= @cart.id
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
      # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'usd',
  })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to root_path
end
  end

  def update
  end

  def destroy
  end

  def edit
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  after_create :UserMailer.welcome_email(self).deliver_now
  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		 @user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/join_table_cart_items_helper.rb
module JoinTableCartItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<h1>Carts#index</h1>
<p>Find me in app/views/carts/index.html.erb</p>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<h2> Panier </h2>
<ul>
	<% @cart.join_table_cart_items.each do |join| %>
	<li><%= join.item.title %></li>


	<strong>Ajouter le: <%= join.created_at%></strong>
	<li >Titre: "<%= join.item.title %>"</li> 
	<li>Description: "<%= join.item.description %>"</li> 
	<li>Prix: "<%= join.item.price %> $ "</li> 
	<li>Image_url :  "<%= join.item.image_url %>"</li>
	<%= link_to "Enlever du panier", join,  method: :delete, data: {confirm: "Etes-vous sûr"}, class: "btn btn-danger" %>
	<br>
	<br>
	<% end %>
</ul>
<br>
<strong> prix total à payer: <%= @sum %> $</strong><br>
<p ><%= link_to "Retour aux produits", root_path%></p>



          <script
            src="https://checkout.stripe.com/checkout.js"
            class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
           
            data-amount="<% @sum %>"
            data-currency="EUR"
            data-locale="auto"></script>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Bienvenue dans Catto</h1>
<%if user_signed_in?%>
  <!-- find if currend_user has a cart else it create a cart for the user -->
	<% cart = Cart.find_by(user_id:current_user.id)
		if !cart
			Cart.create(user_id:current_user.id)
		end	
	%>
	<a href="<%=cart_path(Cart.find_by(user_id:current_user.id ))%>">mon panier</a>
<%end%>
     <% @items.each do |item| %>
	     <p>Titre: "<%= item.title %>"</p> 
	     <p>Description: "<%= item.description %>"</p> 
	     <p>Prix: "<%= item.price %> $"</p> 
	     <p>Image_url :  "<%= item.image_url %>"</p> 
	     <img src="<%= item.image_url %>">
	    
	     <button> <%= link_to "afficher", item_path(item.id)%> </button>
	     <%if user_signed_in?%>
	     <button id='<%=item.id%>' class="add">ajout a mon panier</button>
	     <%end%>
	     <h1>nextItem</h1>
     <%end%>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>
	     <p>Titre: "<%= @item.title %>"</p> 
	     <p>Description: "<%= @item.description %>"</p> 
	     <p>Prix: "<%= @item.price %> $ "</p> 
	     <p>Image_url :  "<%= @item.image_url %>"</p>
<%if user_signed_in?%>
	    <button id='<%=@item.id%>' class="add">ajout a mon panier</button>
<%end%>

app/views/join_table_cart_items/create.html.erb
<div class="notice">
	essaie

</div>

app/views/join_table_cart_items/destroy.html.erb
<h1>JoinTableCartItems#destroy</h1>
<p>Find me in app/views/join_table_cart_items/destroy.html.erb</p>

app/views/join_table_cart_items/edit.html.erb
<h1>JoinTableCartItems#edit</h1>
<p>Find me in app/views/join_table_cart_items/edit.html.erb</p>

app/views/join_table_cart_items/index.html.erb
<h1>JoinTableCartItems#index</h1>
<p>Find me in app/views/join_table_cart_items/index.html.erb</p>

app/views/join_table_cart_items/new.html.erb
<h1>JoinTableCartItems#new</h1>
<p>Find me in app/views/join_table_cart_items/new.html.erb</p>

app/views/join_table_cart_items/show.html.erb
<h1>JoinTableCartItems#show</h1>
<p>Find me in app/views/join_table_cart_items/show.html.erb</p>

app/views/join_table_cart_items/update.html.erb
<h1>JoinTableCartItems#update</h1>
<p>Find me in app/views/join_table_cart_items/update.html.erb</p>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/users/show.html.erb
email: <%= @user.email %><br><br>
first name :  <%= @user.first_name %><br><br>
last name:  <%= @user.last_name %><br><br>
description:   <%= @user.description %><br><br>
age:  <%= @user.age %>